export * from "./iso.js";
export {
  ORIGINAL_DEMOLITION_INITIAL_PROGRESS,
  advanceOriginalDemolitionTick,
  calculateProjectDemolitionRefund,
  createDemolitionState,
  getOriginalDemolitionPhase,
  replayOriginalDemolitionDecrement,
  type DemolitionDecrementResult,
  type DemolitionTickResult,
} from "./demolition.js";
export { getEnvironmentLightLevel, getEnvironmentSightMultiplier } from "./environment.js";
export {
  advanceProjectileSystem,
  createProjectileRegistry,
  createProjectileRegistryWithK01RyuSubtype0c,
  createProjectileSystemState,
  parseSerializedProjectileImpactLog,
  parseSerializedProjectileSystemState,
  K01_RYU_SUBTYPE_0C_PROJECTILE_PROFILE,
  PRODUCT_COORDINATE_ROUND_TRANSFORM_ID,
  PRODUCT_IMMEDIATE_PROJECTILE_PROFILE,
  PRODUCT_LINEAR_PROJECTILE_PROFILE,
  PRODUCT_PROJECTILE_REGISTRY,
  spawnProjectile,
  type AdvanceProjectileSystemResult,
  type CreateProjectileRegistryInput,
  type ProjectileCollisionPolicy,
  type ProjectileCollisionOutcome,
  type ProjectileCoordinateTransform,
  type ProjectileImpactEvent,
  type ProjectileImpactLogEntry,
  type ProjectileImpactPolicy,
  type ProjectileJson,
  type ProjectileJsonRecord,
  type ProjectileMotionAdvance,
  type ProjectileMotionPolicy,
  type ProjectileMotionState,
  type ProjectilePoint,
  type ProjectileProfile,
  type ProjectilePolicyBinding,
  type ProjectilePolicyData,
  type ProjectileRegistry,
  type ProjectileState,
  type ProjectileSystemState,
  type ProjectileTargetReference,
  type SpawnProjectileRequest,
} from "./projectiles.js";
export {
  COMBAT_PROJECTILE_PAYLOAD_SCHEMA,
  COMBAT_PROJECTILE_PAYLOAD_VERSION,
  resolveCombatProjectileImpacts,
  resolveProjectileDeliveryProfileId,
  spawnCombatProjectile,
} from "./projectileCombat.js";
export * from "./world.js";
export {
  K01_ACCEPTED_UPDATE_COUNT_MAX,
  K01_ACCEPTED_UPDATE_COUNT_MIN,
  K01_SOURCE_ENTITY_SLOT_MAX,
  K01_SOURCE_ENTITY_SLOT_MIN,
  K01_SOURCE_GENERATION_MAX,
  K01_SOURCE_GENERATION_MIN,
  K01_SOURCE_HEALTH_MAX,
  K01_SOURCE_HEALTH_MIN,
  K01_SOURCE_RUNTIME_PROFILE_ID,
  K01_SOURCE_RUNTIME_STATE_VERSION,
  cloneSourceRuntimeProfileEnvelope,
  createK01SourceRuntimeState,
  createSourceRuntimeProfileEnvelope,
  defaultSourceRuntimeProfileRegistry,
  parseSourceRuntimeProfileEnvelope,
  registerSourceRuntimeProfile,
  requireSourceRuntimeProfile,
  resolveSourceRuntimeProfileId,
  SourceRuntimeProfileRegistry,
  updateK01SourceRuntimeState,
  validateSourceRuntimeProfileEnvelope,
  validateK01SourceRuntimeState,
  type K01SourceEntityState,
  type K01SourceRuntimeState,
  type K01SourceRuntimeStatePatch,
  type RegisterSourceRuntimeProfileOptions,
  type SourceRuntimeProfile,
} from "./k01SourceRuntimeProfile.js";
export { SkirmishAiController, SKIRMISH_AI_TUNING, type SkirmishAiControllerOptions, type SkirmishAiDifficulty, type SkirmishAiTuning } from "./skirmishAi.js";
export {
  CORE_CURRENT_VISIBILITY_SKIRMISH_AI_PERCEPTION_POLICY_ID,
  CORE_OMNISCIENT_SKIRMISH_AI_PERCEPTION_POLICY_ID,
  getSkirmishAiPerceptionPolicy,
  registerSkirmishAiPerceptionPolicy,
  type SkirmishAiPerceptionContext,
  type SkirmishAiPerceptionPolicy,
} from "./skirmishAiPerception.js";
export {
  BUILTIN_IDLE_COMBAT_POLICY_ID,
  getIdleCombatPolicy,
  registerIdleCombatPolicy,
  type IdleCombatPolicy,
  type IdleCombatPolicyContext,
} from "./idleCombatPolicy.js";
export {
  K01_RYU_ACTION_40_MANA_COST,
  K01_RYU_AUTO_ABILITY_PROFILE_ID,
  K01_RYU_PROJECT_MANA_POOL,
  getAutoAbilityPolicyForUnit,
  registerAutoAbilityPolicy,
  type AutoAbilityPolicy,
  type AutoAbilityPolicyContext,
} from "./autoAbilityPolicy.js";
export {
  BUILTIN_BALANCED_SKIRMISH_AI_STRATEGY_ID,
  getSkirmishAiStrategy,
  registerSkirmishAiStrategy,
  type SkirmishAiStrategy,
  type SkirmishAiStrategyContext,
} from "./skirmishAiStrategy.js";
