import {
  actionDefinitions,
  factionDefinitions,
  resourceDefinitions,
  terrainDefinitions,
  unitDefinitions,
  type ActionDefinition,
  type FactionDefinition,
  type ResourceDefinition,
  type TerrainDefinition,
  type UnitDefinition,
} from "./content.js";
import type { EnvironmentVisualProfile, ResourceVisualSetDefinition, TilesetDefinition } from "./tilesets.js";

const KNOWN_DAMAGE_TYPES = new Set(["physical", "fire", "lightning", "drowning"]);

export interface ContentPackDefinition {
  id: string;
  displayName: string;
  version: string;
  terrains?: Record<string, TerrainDefinition>;
  factions?: Record<string, FactionDefinition>;
  resources?: Record<string, ResourceDefinition>;
  actions?: Record<string, ActionDefinition>;
  units?: Record<string, UnitDefinition>;
  tilesets?: Record<string, TilesetDefinition>;
  environmentVisualProfiles?: Record<string, EnvironmentVisualProfile>;
  resourceVisualSets?: Record<string, ResourceVisualSetDefinition>;
}

export interface ContentRegistry {
  packs: readonly ContentPackDefinition[];
  terrains: Record<string, TerrainDefinition>;
  factions: Record<string, FactionDefinition>;
  resources: Record<string, ResourceDefinition>;
  actions: Record<string, ActionDefinition>;
  units: Record<string, UnitDefinition>;
  tilesets: Record<string, TilesetDefinition>;
  environmentVisualProfiles: Record<string, EnvironmentVisualProfile>;
  resourceVisualSets: Record<string, ResourceVisualSetDefinition>;
}

export interface ContentValidationIssue {
  path: string;
  message: string;
  severity: "error" | "warning";
}

export interface ContentValidationResult {
  ok: boolean;
  issues: ContentValidationIssue[];
}

export const coreContentPack = {
  id: "isorts-core",
  displayName: "ISORTS Core",
  version: "0.1.0",
  terrains: terrainDefinitions,
  factions: factionDefinitions,
  resources: resourceDefinitions,
  actions: actionDefinitions,
  units: unitDefinitions,
  tilesets: {
    "core-default": {
      id: "core-default",
      displayName: "Core Default",
      terrainAssets: {},
      evidenceStatus: "source-backed-adaptation",
    },
  },
  environmentVisualProfiles: {
    "core-default": {
      id: "core-default",
      displayName: "Core Default",
      evidenceStatus: "source-backed-adaptation",
    },
  },
  resourceVisualSets: {
    "core-default": {
      id: "core-default",
      displayName: "Core Default",
      resources: {},
      evidenceStatus: "source-backed-adaptation",
    },
  },
} as const satisfies ContentPackDefinition;

const sourceAssetHashes = {
  normal: {
    grss1: "1e64a36addc74734bdbb24fa368ad70740c806a6bdc823419bab8f5286aea965",
    sea0: "5349dd452198bde4f67264faa8152c51a1e91afb93669f72d0d9b72db707229e",
    hill0: "b8acdf64ba5a3c0fa9129e8546fe595fff7cdd83edbab05195a473ea650ff7b7",
  },
  snow: {
    grss1: "68c100ee1a6ddffb646978207859abaa03e7e7df661bc64b843e036358669868",
    sea0: "a0e6ce0acfc57a610512ccbb58dbd8cb55de81a7ae5ed602b8f24a9a715e1d3a",
    hill0: "08a8d6b25926225b524b841b313098a35f718d8751fda76ba052c0e58474f18a",
  },
  brown: {
    grss1: "ad70db81325d9b297c06645d298ef77ed710ad17432be45b98a1560f137a5a3f",
    sea0: "5349dd452198bde4f67264faa8152c51a1e91afb93669f72d0d9b72db707229e",
    hill0: "5e512bec4b95cfc18e7f0fd58da825eea31b2c057dd3cdab62c8d81862c92a68",
  },
} as const;

// Files and hashes are generated by `extract-imjinrok-environment-assets.mjs`.
// They catalogue source files only; they do not assert original tile selection,
// resource placement, palette timing, or resource-to-sprite semantics.
export const imjinrokSourceContentPack = {
  id: "imjinrok-source-assets",
  displayName: "Imjinrok Source Asset Catalog",
  version: "0.1.0",
  terrains: {},
  factions: {},
  resources: {},
  actions: {},
  units: {},
  tilesets: {
    "imjinrok-normal": createImjinrokTileset("normal"),
    "imjinrok-snow": createImjinrokTileset("snow"),
    "imjinrok-brown": createImjinrokTileset("brown"),
  },
  environmentVisualProfiles: {
    "imjinrok-source-night-catalog": {
      id: "imjinrok-source-night-catalog",
      displayName: "Imjinrok Night Palette Catalog",
      paletteAssets: [
        { url: "/assets/themes/default/environment/imjinrok-night/night1.pal.json", frame: 0 },
        { url: "/assets/themes/default/environment/imjinrok-night/night2.pal.json", frame: 0 },
        { url: "/assets/themes/default/environment/imjinrok-night/night3.pal.json", frame: 0 },
        { url: "/assets/themes/default/environment/imjinrok-night/night4.pal.json", frame: 0 },
      ],
      evidenceStatus: "unresolved",
      sourceAssets: [
        sourceAsset("pal/night1.pal", "b085583412b8bb79bdf9b72d836881be37f6f36ad50d073db06bebd1c2670122"),
        sourceAsset("pal/night2.pal", "c45727bd8ffed04bf572da5ab38b14b7fcb819f540a15a2e5d13730357bda17d"),
        sourceAsset("pal/night3.pal", "4fe0c28dc64480c6f00876c5ee484e1b3caa77b3b63b27387c6cf7702c3d2f97"),
        sourceAsset("pal/night4.pal", "f8328d22007407df426dff9e489f43718e28772d03b3ddd5f663a5dd57156e95"),
        sourceAsset("tempeft/night1.YAV", "d31f2603ffc00e004911ab8b811c6603764798c1b5950a91e12288dab1f54f5f"),
      ],
    },
  },
  resourceVisualSets: {
    "imjinrok-source-resource-adaptation": {
      id: "imjinrok-source-resource-adaptation",
      displayName: "Imjinrok Resource Source-Asset Candidates",
      resources: {
        rice: sourceResourceVisual("crop0"),
        potato: sourceResourceVisual("crop0"),
        tree: sourceResourceVisual("tree0"),
        bamboo: sourceResourceVisual("tree0"),
        gold: sourceResourceVisual("resource"),
        stone: sourceResourceVisual("resource"),
      },
      evidenceStatus: "unresolved",
      sourceAssets: [
        sourceAsset("fnt/crop0.spr", "ca91364c8b43f36974c591cac29f5a0610832bd9a9e5a6700d41d51225fbdc00"),
        sourceAsset("fnt/tree0.spr", "871c0572134266838776bd3e90005287a14abfb3c56f5e9c2dab80f1aaa1c2fc"),
        sourceAsset("fnt/resource.spr", "04a2c1608a64a91922193c82a67895d00391e59cb9faa31b5916238f9416ff40"),
      ],
    },
  },
} as const satisfies ContentPackDefinition;

export const defaultContentPacks = [coreContentPack, imjinrokSourceContentPack] as const;

export function createContentRegistry(packs: readonly ContentPackDefinition[] = defaultContentPacks): ContentRegistry {
  return {
    packs,
    terrains: mergeDefinitions(packs.map((pack) => pack.terrains ?? {})),
    factions: mergeDefinitions(packs.map((pack) => pack.factions ?? {})),
    resources: mergeDefinitions(packs.map((pack) => pack.resources ?? {})),
    actions: mergeDefinitions(packs.map((pack) => pack.actions ?? {})),
    units: mergeDefinitions(packs.map((pack) => pack.units ?? {})),
    tilesets: mergeDefinitions(packs.map((pack) => pack.tilesets ?? {})),
    environmentVisualProfiles: mergeDefinitions(packs.map((pack) => pack.environmentVisualProfiles ?? {})),
    resourceVisualSets: mergeDefinitions(packs.map((pack) => pack.resourceVisualSets ?? {})),
  };
}

function createImjinrokTileset(theme: "normal" | "snow" | "brown"): TilesetDefinition {
  const root = `/assets/themes/default/terrain/imjinrok-${theme}`;

  return {
    id: `imjinrok-${theme}`,
    displayName: `Imjinrok ${theme} Source Asset Catalog`,
    terrainAssets: {
      grass: { url: `${root}/grss1_0000.png`, frame: 0 },
      water: { url: `${root}/sea0_0000.png`, frame: 0 },
    },
    elevationAssets: {
      "1": { url: `${root}/hill0_0000.png`, frame: 0 },
    },
    evidenceStatus: "unresolved",
    sourceAssets: [
      sourceAsset(`tile/${theme}/grss1.ytl`, sourceAssetHashes[theme].grss1),
      sourceAsset(`tile/${theme}/sea0.ytl`, sourceAssetHashes[theme].sea0),
      sourceAsset(`tile/${theme}/hill0.ytl`, sourceAssetHashes[theme].hill0),
    ],
  };
}

function sourceAsset(sourcePath: string, sha256: string) {
  return { sourcePath, sha256 };
}

function sourceResourceVisual(stem: "crop0" | "tree0" | "resource"): ResourceVisualSetDefinition["resources"][string] {
  const asset = { url: `/assets/themes/default/resources/imjinrok/${stem}_0000.png`, frame: 0 };

  return { states: { active: asset, depleted: asset }, evidenceStatus: "unresolved" };
}

export function validateContentRegistry(registry: ContentRegistry): ContentValidationResult {
  const issues: ContentValidationIssue[] = [];

  registry.packs.forEach((pack, index) => {
    issues.push(...validateContentPackMetadata(pack, `packs[${index}]`));
  });

  validateDefinitionIds(registry.terrains, "terrains", issues);
  validateDefinitionIds(registry.factions, "factions", issues);
  validateDefinitionIds(registry.resources, "resources", issues);
  validateDefinitionIds(registry.actions, "actions", issues);
  validateDefinitionIds(registry.units, "units", issues);
  validateDefinitionIds(registry.tilesets, "tilesets", issues);
  validateDefinitionIds(registry.environmentVisualProfiles, "environmentVisualProfiles", issues);
  validateDefinitionIds(registry.resourceVisualSets, "resourceVisualSets", issues);
  validateResourceDefinitions(registry, issues);
  validateUnitDefinitions(registry, issues);

  return toValidationResult(issues);
}

export function validateContentPack(pack: ContentPackDefinition): ContentValidationResult {
  return validateContentRegistry(createContentRegistry([pack]));
}

function mergeDefinitions<TDefinition>(definitionSets: readonly Record<string, TDefinition>[]): Record<string, TDefinition> {
  return Object.assign({}, ...definitionSets);
}

function validateContentPackMetadata(pack: ContentPackDefinition, path: string): ContentValidationIssue[] {
  const issues: ContentValidationIssue[] = [];

  if (!pack.id.trim()) {
    issues.push(createIssue(`${path}.id`, "Content pack id is required."));
  }

  if (!pack.displayName.trim()) {
    issues.push(createIssue(`${path}.displayName`, "Content pack display name is required."));
  }

  if (!pack.version.trim()) {
    issues.push(createIssue(`${path}.version`, "Content pack version is required."));
  }

  return issues;
}

function validateDefinitionIds(
  definitions: Record<string, { id: string }>,
  path: string,
  issues: ContentValidationIssue[],
): void {
  for (const [key, definition] of Object.entries(definitions)) {
    if (!definition.id.trim()) {
      issues.push(createIssue(`${path}.${key}.id`, "Definition id is required."));
      continue;
    }

    if (definition.id !== key) {
      issues.push(createIssue(`${path}.${key}.id`, `Definition id '${definition.id}' must match key '${key}'.`));
    }
  }
}

const knownBankResourceKinds = new Set(["food", "wood", "gold", "stone"]);

function validateResourceDefinitions(registry: ContentRegistry, issues: ContentValidationIssue[]): void {
  for (const [resourceId, definition] of Object.entries(registry.resources)) {
    if (!definition.displayName.trim()) {
      issues.push(createIssue(`resources.${resourceId}.displayName`, "Resource display name is required."));
    }

    if (!definition.category.trim()) {
      issues.push(createIssue(`resources.${resourceId}.category`, "Resource category is required."));
    }

    if (!knownBankResourceKinds.has(definition.yieldResource)) {
      issues.push(createIssue(`resources.${resourceId}.yieldResource`, `Unknown bank resource '${definition.yieldResource}'.`));
    }

    if (!Number.isFinite(definition.capacity) || definition.capacity <= 0) {
      issues.push(createIssue(`resources.${resourceId}.capacity`, "Resource capacity must be a positive number."));
    }

    if (!Number.isFinite(definition.gatherAmountPerTick) || definition.gatherAmountPerTick <= 0) {
      issues.push(createIssue(`resources.${resourceId}.gatherAmountPerTick`, "Gather amount per tick must be a positive number."));
    }

    validateResourcePlaceholderVisual(definition, resourceId, issues);
    validateResourceOccupancy(definition.activeOccupancy, `resources.${resourceId}.activeOccupancy`, issues);

    if (definition.depletion.mode === "stay" && !definition.depletion.depletedOccupancy) {
      issues.push(createIssue(`resources.${resourceId}.depletion.depletedOccupancy`, "Persistent depleted resources must define depleted occupancy."));
    }

    if (definition.depletion.depletedOccupancy) {
      validateResourceOccupancy(definition.depletion.depletedOccupancy, `resources.${resourceId}.depletion.depletedOccupancy`, issues);
    }

    if (!definition.regrowth) {
      continue;
    }

    if (definition.depletion.mode !== "stay") {
      issues.push(createIssue(`resources.${resourceId}.regrowth`, "Regrowing resources must stay on the tile when depleted."));
    }

    if (definition.regrowth.trigger !== "rain") {
      issues.push(createIssue(`resources.${resourceId}.regrowth.trigger`, `Unknown regrowth trigger '${definition.regrowth.trigger}'.`));
    }

    if (!Number.isFinite(definition.regrowth.requiredTicks) || definition.regrowth.requiredTicks <= 0) {
      issues.push(createIssue(`resources.${resourceId}.regrowth.requiredTicks`, "Regrowth ticks must be a positive number."));
    }

    if (typeof definition.regrowth.restoreAmount === "number" && (!Number.isFinite(definition.regrowth.restoreAmount) || definition.regrowth.restoreAmount <= 0)) {
      issues.push(createIssue(`resources.${resourceId}.regrowth.restoreAmount`, "Numeric restore amount must be a positive number."));
    }
  }
}

function validateResourcePlaceholderVisual(
  definition: ResourceDefinition,
  resourceId: string,
  issues: ContentValidationIssue[],
): void {
  const visual = definition.placeholderVisual;

  if (!visual.glyph.trim()) {
    issues.push(createIssue(`resources.${resourceId}.placeholderVisual.glyph`, "Resource placeholder glyph is required."));
  }

  for (const colorKey of ["worldColor", "outlineColor", "minimapColor"] as const) {
    const color = visual[colorKey];

    if (!Number.isInteger(color) || color < 0x000000 || color > 0xffffff) {
      issues.push(createIssue(`resources.${resourceId}.placeholderVisual.${colorKey}`, "Resource placeholder color must be a 24-bit integer."));
    }
  }
}

function validateResourceOccupancy(
  occupancy: ResourceDefinition["activeOccupancy"],
  path: string,
  issues: ContentValidationIssue[],
): void {
  if (typeof occupancy.blocksMovement !== "boolean") {
    issues.push(createIssue(`${path}.blocksMovement`, "Resource movement blocking must be boolean."));
  }

  if (typeof occupancy.blocksBuilding !== "boolean") {
    issues.push(createIssue(`${path}.blocksBuilding`, "Resource building blocking must be boolean."));
  }
}

function validateUnitDefinitions(registry: ContentRegistry, issues: ContentValidationIssue[]): void {
  for (const [unitId, definition] of Object.entries(registry.units)) {
    if (!Number.isFinite(definition.footprint.width) || definition.footprint.width <= 0) {
      issues.push(createIssue(`units.${unitId}.footprint.width`, "Footprint width must be a positive number."));
    }

    if (!Number.isFinite(definition.footprint.height) || definition.footprint.height <= 0) {
      issues.push(createIssue(`units.${unitId}.footprint.height`, "Footprint height must be a positive number."));
    }

    if (definition.combat) {
      validatePositiveNumber(definition.combat.damage, `units.${unitId}.combat.damage`, issues);
      validatePositiveNumber(definition.combat.range, `units.${unitId}.combat.range`, issues);
      validatePositiveNumber(definition.combat.cooldownTicks, `units.${unitId}.combat.cooldownTicks`, issues);
      validatePositiveNumber(definition.combat.aggroRange, `units.${unitId}.combat.aggroRange`, issues);

      if (definition.combat.damageType !== undefined && !KNOWN_DAMAGE_TYPES.has(definition.combat.damageType)) {
        issues.push(createIssue(`units.${unitId}.combat.damageType`, `Unknown damage type '${definition.combat.damageType}'.`));
      }

      if (definition.combat.aggroRange < definition.combat.range) {
        issues.push(createIssue(`units.${unitId}.combat.aggroRange`, "Aggro range must be at least attack range."));
      }
    }

    for (const [resource, amount] of Object.entries(definition.cost ?? {})) {
      if (!knownBankResourceKinds.has(resource)) {
        issues.push(createIssue(`units.${unitId}.cost.${resource}`, `Unknown bank resource '${resource}'.`));
        continue;
      }

      validatePositiveNumber(amount, `units.${unitId}.cost.${resource}`, issues);
    }

    const hotkeysByActionId = new Map<string, string>();

    for (const actionId of definition.actionIds) {
      const action = registry.actions[actionId];

      if (!action) {
        issues.push(createIssue(`units.${unitId}.actionIds`, `Unknown action '${actionId}'.`));
        continue;
      }

      const hotkey = action.hotkey.trim().toUpperCase();

      if (!hotkey) {
        issues.push(createIssue(`actions.${actionId}.hotkey`, "Action hotkey is required."));
        continue;
      }

      const conflictingActionId = hotkeysByActionId.get(hotkey);

      if (conflictingActionId) {
        issues.push(createIssue(
          `units.${unitId}.actionIds`,
          `Actions '${conflictingActionId}' and '${actionId}' share hotkey '${hotkey}'.`,
        ));
        continue;
      }

      hotkeysByActionId.set(hotkey, actionId);
    }

    if (definition.category === "building" && !definition.placement) {
      issues.push(createIssue(`units.${unitId}.placement`, "Building units should define placement rules.", "warning"));
    }

    for (const terrainId of definition.placement?.allowedTerrain ?? []) {
      if (!registry.terrains[terrainId]) {
        issues.push(createIssue(`units.${unitId}.placement.allowedTerrain`, `Unknown terrain '${terrainId}'.`));
      }
    }
  }
}

function validatePositiveNumber(value: number, path: string, issues: ContentValidationIssue[]): void {
  if (!Number.isFinite(value) || value <= 0) {
    issues.push(createIssue(path, "Value must be a positive number."));
  }
}

function createIssue(
  path: string,
  message: string,
  severity: ContentValidationIssue["severity"] = "error",
): ContentValidationIssue {
  return { path, message, severity };
}

function toValidationResult(issues: ContentValidationIssue[]): ContentValidationResult {
  return {
    ok: !issues.some((issue) => issue.severity === "error"),
    issues,
  };
}
