import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), "../..");
const scriptPath = join(repositoryRoot, "tools/imjinrok/trace-ui-callsite-debugger.ps1");

test("UI callsite debugger helper uses marker-scoped direct Debug API capture", () => {
  const script = readFileSync(scriptPath, "utf8");

  assert.match(script, /param\(/);
  assert.match(script, /\[string\]\$Marker/);
  assert.match(script, /\[string\]\$Mode = "int3"/);
  assert.match(script, /DebugActiveProcess/);
  assert.match(script, /DebugActiveProcessStop/);
  assert.match(script, /CreateProcess/);
  assert.match(script, /WaitForDebugEvent/);
  assert.match(script, /ContinueDebugEvent/);
  assert.match(script, /EXIT_PROCESS_DEBUG_EVENT/);
  assert.match(script, /EXIT_PROCESS_DEBUG_INFO/);
  assert.match(script, /exitCode/);
  assert.match(script, /Wow64GetThreadContext/);
  assert.match(script, /Wow64SetThreadContext/);
  assert.match(script, /WriteProcessMemory/);
  assert.match(script, /0xcc/);
  assert.match(script, /direct-windows-debug-api-int3-runtime-probe/);
  assert.match(script, /target-exited/);
  assert.match(script, /helper-error/);
  assert.match(script, /helperError/);
  assert.match(script, /unhandled-error/);
  assert.match(script, /scriptStackTrace/);
  assert.match(script, /Write-RecordSnapshot/);
  assert.match(script, /eventsSeenTail/);
  assert.match(script, /ConvertTo-DwordTrace/);
  assert.match(script, /Read-AsciiCandidate/);
  assert.match(script, /stackDwords/);
  assert.match(script, /registerPointers/);
});

test("UI callsite debugger helper can launch the target under debug from process start", () => {
  const script = readFileSync(scriptPath, "utf8");

  assert.match(script, /\[string\]\$LaunchExecutable = ""/);
  assert.match(script, /\[string\]\$LaunchWorkDir = ""/);
  assert.match(script, /\[switch\]\$StopTargetOnExit/);
  assert.match(script, /Start-DebuggedProcess/);
  assert.match(script, /DEBUG_ONLY_THIS_PROCESS/);
  assert.match(script, /launched-under-debug/);
  assert.match(script, /direct-createprocess-debug/);
  assert.match(script, /initialThreadId/);
  assert.match(script, /targetInitialThreadId/);
  assert.match(script, /LaunchExecutable currently requires -Mode hardware/);
});

test("UI callsite debugger helper can use non-mutating hardware breakpoints", () => {
  const script = readFileSync(scriptPath, "utf8");

  assert.match(script, /SuspendThread/);
  assert.match(script, /ResumeThread/);
  assert.match(script, /Dr0/);
  assert.match(script, /Dr7/);
  assert.match(script, /EXCEPTION_SINGLE_STEP/);
  assert.match(script, /EXCEPTION_WOW64_SINGLE_STEP/);
  assert.match(script, /1073741854/);
  assert.match(script, /CREATE_THREAD_DEBUG_EVENT/);
  assert.match(script, /Hardware mode supports at most four call-sites/);
  assert.match(script, /direct-windows-debug-api-hardware-breakpoint-runtime-probe/);
  assert.match(script, /threadBreakpointClearResults/);
  assert.match(script, /cleared = \$false/);
  assert.match(script, /\$threadBreakpointResults = @\(Set-HardwareBreakpointsOnProcessThreads/);
  assert.match(script, /\$threadBreakpointResults = @\(\$threadBreakpointResults\) \+ @\(Set-HardwareBreakpointsOnThread/);
});

test("UI callsite debugger helper carries binary-derived K01 UI callsite contexts", () => {
  const script = readFileSync(scriptPath, "utf8");

  assert.match(script, /0x004aafda/);
  assert.match(script, /yfnt\\\\selectstageborder\.spr/);
  assert.match(script, /0x004aafeb/);
  assert.match(script, /fields esi\+0x000010ec/);
  assert.match(script, /0x004a51de/);
  assert.match(script, /stack 0x0c=0x119,0x24=0x185/);
  assert.match(script, /0x004aaae3/);
  assert.match(script, /stack 0x0c=0x120,0x34=0x1c2/);
  assert.match(script, /hud-resource-candidates/);
  assert.match(script, /hud-resource-candidates-no-hero/);
  assert.match(script, /0x004a577a/);
  assert.match(script, /yfnt\\\\objectiveborder\.spr/);
  assert.match(script, /0x004a7445/);
  assert.match(script, /yfnt\\\\hero\.spr/);
  assert.match(script, /0x004a952d/);
  assert.match(script, /ProgressBar_Small\.spr/);
  assert.match(script, /0x004ac3bd/);
  assert.match(script, /yfnt\\\\gamespeed\.spr/);
  assert.match(script, /hud-hero-panel-draw-candidates/);
  assert.match(script, /0x004a76d0/);
  assert.match(script, /0x004a8870/);
  assert.match(script, /0x004a887f/);
  assert.match(script, /0x00c83e00/);
  assert.match(script, /hud-hero-panel-frame-candidates/);
  assert.match(script, /hud-hero-panel-draw-only-candidates/);
  assert.match(script, /hud-hero-panel-final-draw-candidates/);
  assert.match(script, /0x004a7716/);
  assert.match(script, /0x0044abb0/);
  assert.match(script, /0x004a773d/);
  assert.match(script, /0x0044c8c0/);
  assert.match(script, /0x004a7758/);
  assert.match(script, /0x00c84348/);
  assert.match(script, /0x004a7778/);
  assert.match(script, /0x0044dfd0/);
  assert.match(script, /0x004a778a/);
  assert.match(script, /0x0044ada0/);
  assert.match(script, /0x004a77f3/);
  assert.match(script, /0x004414a0/);
  assert.match(script, /0x004a783d/);
  assert.match(script, /hud-nonhero-draw-candidates/);
  assert.match(script, /hud-objective-draw-candidates/);
  assert.match(script, /hud-progress-draw-candidates/);
  assert.match(script, /hud-selected-progress-candidates/);
  assert.match(script, /hud-selected-production-text-candidates/);
  assert.match(script, /hud-selected-slot-dispatch-candidates/);
  assert.match(script, /hud-bottom-panel-text-candidates/);
  assert.match(script, /hud-bottom-panel-value-draw-candidates/);
  assert.match(script, /hud-bottom-panel-label-draw-candidates/);
  assert.match(script, /hud-bottom-panel-extra-line-candidates/);
  assert.match(script, /hud-game-speed-draw-candidates/);
  assert.match(script, /hud-game-speed-frame-only-candidates/);
  assert.match(script, /0x004a5a10/);
  assert.match(script, /0x0088b498/);
  assert.match(script, /0x004a967b/);
  assert.match(script, /0x00c8567c/);
  assert.match(script, /0x004a96b5/);
  assert.match(script, /0x004a7880/);
  assert.match(script, /0x004a79b8/);
  assert.match(script, /0x51eb851f/);
  assert.match(script, /0x004a8564/);
  assert.match(script, /0x004a84e0/);
  assert.match(script, /0x004a8511/);
  assert.match(script, /0x004a8534/);
  assert.match(script, /0x004a81f0/);
  assert.match(script, /0x004a8278/);
  assert.match(script, /0x004a83e7/);
  assert.match(script, /0x004567c0/);
  assert.match(script, /0x0045687f/);
  assert.match(script, /0x00456e16/);
  assert.match(script, /0x00456e32/);
  assert.match(script, /0x00456e57/);
  assert.match(script, /0x00456e7b/);
  assert.match(script, /0x00456f6b/);
  assert.match(script, /0x00456f9b/);
  assert.match(script, /0x004570cc/);
  assert.match(script, /0x004571fd/);
  assert.match(script, /0x0045732e/);
  assert.match(script, /0x0045738b/);
  assert.match(script, /0x004573af/);
  assert.match(script, /0x004573cd/);
  assert.match(script, /0x00457438/);
  assert.match(script, /\[esi\+0x294\]/);
  assert.match(script, /\[esi\+0x114 \+ n\*0x80\]/);
  assert.match(script, /0x004ac5ac/);
  assert.match(script, /0x004ac5b1/);
  assert.match(script, /0x004ac5db/);
  assert.match(script, /0x00cd9048/);
});
